import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#6b7280',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  errorEmoji: {
    fontSize: 64,
    marginBottom: 16,
  },
  errorTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 24,
  },
  retryButton: {
    backgroundColor: '#3b82f6',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  retryText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  familyCard: {
    backgroundColor: '#fff',
    margin: 16,
    padding: 20,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  familyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  familyEmoji: { fontSize: 48, marginRight: 16 },
  familyInfo: { flex: 1 },
  familyName: { fontSize: 20, fontWeight: '700', color: '#1a1a2e' },
  memberCount: { fontSize: 14, color: '#6b7280', marginTop: 2 },
  ownerBadge: {
    backgroundColor: '#fef3c7',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  ownerText: { fontSize: 12, fontWeight: '600', color: '#d97706' },

  balanceSection: { marginBottom: 1 },
  balanceLabel: { fontSize: 14, color: '#6b7280', marginBottom: 9 },
  balanceAmount: { fontSize: 24, fontWeight: '700', color: '#059669' },

  inviteSection: {
    marginTop: 16,
    paddingTop: 16,
  },
  inviteLabel: { fontSize: 14, color: '#6b7280', marginBottom: 8 },
  inviteCodeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  inviteCode: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    color: '#3b82f6',
    backgroundColor: '#eff6ff',
    padding: 12,
    borderRadius: 8,
    textAlign: 'center',
    letterSpacing: 2,
  },
  shareButton: {
    backgroundColor: '#3b82f6',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    marginLeft: 12,
  },
  shareText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  refreshCodeButton: { alignSelf: 'flex-start' },
  refreshCodeText: {
    fontSize: 14,
    color: '#6b7280',
    textDecorationLine: 'none',
  },

  membersCard: {
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 20,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a1a2e',
    marginBottom: 16,
  },

  memberItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  memberAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#3b82f6',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  memberAvatarText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  memberInfo: { flex: 1 },
  memberName: { fontSize: 16, fontWeight: '600', color: '#1a1a2e' },
  memberRole: { fontSize: 12, color: '#6b7280', marginTop: 2 },
  memberStats: { alignItems: 'flex-end' },
  memberSpent: { fontSize: 12, color: '#ef4444' },
  memberContrib: { fontSize: 12, color: '#059669', marginTop: 2 },

  actionsCard: {
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 20,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  actionEmoji: { fontSize: 24, marginRight: 16, width: 32 },
  actionText: { fontSize: 16, color: '#374151' },

  leaveButton: {
    marginHorizontal: 16,
    marginTop: 32,
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: 'center',
  },
  leaveText: {
    color: '#ef4444',
    fontSize: 16,
    fontWeight: '600',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    borderBottomWidth: 1,
  },
  headerDark: {
    backgroundColor: '#FF69B4',
  },
  headerLight: {
    backgroundColor: '#FFD6E8',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    flex: 1,
    textAlign: 'center',
  },
  ownerActionsCard: {
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginBottom: 32,
    padding: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#fee2e2',
  },
  dangerTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#b91c1c',
    marginBottom: 16,
  },
  transferButton: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  transferText: {
    fontSize: 16,
    color: '#d97706',
    fontWeight: '600',
  },
  disbandButton: {
    paddingVertical: 12,
    marginTop: 4,
    flexDirection: 'row',
    gap: 6,
  },
  disbandText: {
    fontSize: 16,
    color: '#ef4444',
    fontWeight: '600',
  },
  removeMemberButton: {
    padding: 4,
    marginLeft: 8,
  },
  removeMemberText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  menuButton: {
    padding: 4,
    marginLeft: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuCard: {
    width: 260,
    borderRadius: 12,
    paddingVertical: 8,
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  menuMemberName: {
    fontSize: 14,
    fontWeight: '600',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  menuItemText: {
    fontSize: 15,
  },
});

export default styles;
